[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "good_music_bot"
version = "1.3.2"
description = "A discord music bot powered by discord.py"
readme = "README.md"

requires-python = ">=3.8"
dependencies = [
    "discord.py[voice]",
    "python-dotenv",
    "youtube_dl",
]